baseURL = 'https://net.chenayin.com/'
languageCode = 'zh-CN'
title = '别人打药我拽管'

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        version = "v0.2.0"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false
		version = "v5.20300.20400"
[params.docs]
  prismTheme = "lucario"