[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.148.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "false"
  HUGO_EXTENDED = "true"  # ✅ 关键：启用 Hugo Extended 版本