[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.148.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "false"

# 关键：启用 extended 版本
[context.production]
  environment = { HUGO_VERSION = "0.148.1", HUGO_EXTENDED = "true" }